import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import clsx from "clsx";
import { Icon, IconKey } from "@/components/icon/Icon";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface BottomBarBtnProps {
  icon: IconKey;
  label: string;
}
const BottomBarButton = ({ icon, label }: BottomBarBtnProps) => {
  return (
    <>
      <div
        className={clsx(
          "flex flex-col align-middle justify-center w-14 h-14 p-0"
        )}
      >
        <div className={clsx("flex align-middle justify-center")}>
          <Icon type={icon} />
        </div>
        <p className={clsx("text-center")}>{label}</p>
      </div>
    </>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className={clsx("flex flex-col min-h-screen mx-8")}>
          {children}
        </div>
        <div
          className={clsx(
            "fixed bottom-0 w-screen left-0 right-0 flex justify-center gap-2"
          )}
        >
          <BottomBarButton icon="home" label="Inicio"></BottomBarButton>
          <BottomBarButton icon="plin" label="Plin"></BottomBarButton>
          <BottomBarButton icon="qr" label="QR"></BottomBarButton>
          <BottomBarButton icon="gift" label="Para ti"></BottomBarButton>
          <BottomBarButton icon="menu" label="Más"></BottomBarButton>
        </div>
      </body>
    </html>
  );
}
